FROM golang:1.24.0 AS builder

WORKDIR /app

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the binary using linker flags to remove debug info and reduce size
RUN go build -ldflags="-s -w" -o api ./cmd/api

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /app/api /app/api

EXPOSE 8090

ENTRYPOINT ["/app/api"]
